### ISSUE TITLE
Mapping geoflow and Zenodo data types

### ISSUE THREAD

**Issue by juldebar** [eblondel/geoflow#1]
is it possible to modify the [line of  the action in geoflow_action_zen4R_deposit_record.R where the data type is hard coded](https://github.com/eblondel/geoflow/blob/fc16673ac5e40ee375f677c4fc83ec841fd79bfe/R/geoflow_action_zen4R_deposit_record.R#L59) since the geoflow_entity class already assign a default value "dataset" in the [line 8](https://github.com/eblondel/geoflow/blob/fc16673ac5e40ee375f677c4fc83ec841fd79bfe/R/geoflow_entity.R#L8) ?
Something like 
 ``` zenodo_metadata$setUploadType(entity$type)  ``` 
This would enable to either send directly one of the values expected by Zenodo API or to let it empty and get "dataset" as a default value.

**Comment by eblondel** [comment]
Done. Can you check?
