### ISSUE TITLE
datestamp element gets character string type

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#103]
In the xml, the datestamp element looks like :
`<gmd:dateStamp><gco:CharacterString>2021-01-28T15:59:22</gco:CharacterString></gmd:dateStamp>`
DateTime or Date should be used instead of CharacterString so that the metadata can be validated in GeoNetwork.

**Comment by eblondel** [comment]
Thanks @juliepierson i was aware of that one and will tackle it asap. I've to check in depending R packages. Which method did you use for the publication did you use ows4R / CSW or geonapi action?

**Comment by juliepierson** [comment]
I used geoflow actions : "geometa-create-iso-19115" and "ows4R-publish-iso-19139". Thanks !

**Comment by eblondel** [comment]
The issue comes from [geometa](https://github.com/eblondel/geometa) I'm going to have a look and let you know when fixed.

**Comment by juliepierson** [comment]
Thank you !

**Comment by eblondel** [comment]
It has been fixed in geometa, you wil have to reinstall it from github: ``remotes::install_github("eblondel/geometa")``.

**Comment by juliepierson** [comment]
Great, thanks !

**Comment by juliepierson** [comment]
I tested today, it works with our metadata.
