### ISSUE TITLE
CreationDate is always added to metadata

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#104]
When a publication date is stated in the CSV file (publication:2021-02-04), a creation date is automatically added alongside the publication date. It must be manually deleted in order to validate the metadata in GeoNetwork.

**Comment by eblondel** [comment]
We need to discuss that. Geonetwork validation is questionable. The validation that is performed by [geometa](https://github.com/eblondel/geometa) package on ISO 19115/19139 follows the official XML schemas. At last time i've investigated the matter, Geonetwork was using a modifying schema. 

When there is an issue of validation this appears when converting into XML (#103 is an example of validation issue).

**Comment by juliepierson** [comment]
Ok, thanks, I did not know that. Apart from the validation issue, creation date does not apply to our metadata so we need to delete it anyway, we only use publication date.

**Comment by juliepierson** [comment]
Thanks for this commit. I updated geoflow (packageVersion : ‘0.0.20201203’) but creation date is still added, with no publication date, even though the Date column is csv file is like this : publication:2021-01-28. Did I miss something ? Thanks !

**Comment by eblondel** [comment]
If you use Rstudio, be careful with the package updates, RStudio maintains package caches, and even if it looks like you are using the new package, it's not the case in reality. For that make sure to start a brand new R session, install the package and then load it. Normally this issue should be fixed.

**Comment by juliepierson** [comment]
It works now, the error was in my script which rewrote the date in the CSV ! Thanks.
