### ISSUE TITLE
Edition and EditionDate automatically added to XML

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#105]
Both elements get automatically added :
`<gmd:edition><gco:CharacterString>2021-01-28T15:01:24</gco:CharacterString></gmd:edition>`
`<gmd:editionDate><gco:CharacterString>2021-01-28T15:59:24</gco:CharacterString></gmd:editionDate>`
These elements must be manually removed if not needed, or if needed CharacterString must be replaced with DateTime.

**Comment by eblondel** [comment]
Two things here:
* on the ``editionDate``, at now it takes the date when the metadata is edited/created. I'm fine to add a mapping to the Date column in the input entity CSV, but ``edition`` is not part of the data types used in ISO 19115 (The list is ``creation, publication, revision, expiry, lastUpdate, lastRevision, nextUpdate, unavailable, inForce, adopted, deprecated, superseded, validityBegins, validityExpires, released, distribution``, nor in Dublin Core.  I suggest to add it anyway, so you will have to enter the editionDate in the Date column using eg ``edition:2020-01-01``

* for the "edition" which is a supposed to be a version actually, what I did so far is to automate its filling based on the edition date, which is consistent (except the fact that as it is it generates an ISO validation schema issue becauses it treats it as datetime at XML decoding - I should have prepended it with a "v"). We don't manage this yet in the metadata model. One suggestion could be to add a "edition" (or maybe "version") subtype in the Description column, and an input would like ``edition:v1.0.0`` or ``version:v1.0.0``

As both deal with mapping the geoflow metadata model with ISO 19115, this is really an open discussion so @juliepierson @mrouan @wheintz @juldebar your opinion/vote is welcome before I proceed with changes

**Comment by mrouan** [comment]
I vote for :
- editionDate in Date column using edition:2020-01-01
- edition in Description column using edition:v1.0.0
if these element ar not present, the edition and editionDate are created in the XML

**Comment by eblondel** [comment]
ok, thanks,  @juldebar @wheintz what do you think?

**Comment by eblondel** [comment]
@mrouan @juliepierson i've implemented the above proposal. let me know if it works well on your side.

**Comment by juldebar** [comment]
I am not sure about the definition of "edition". My understanding is that it indicates the version of the metadata sheet and the content is free (doesn't have to be a date).
If it is the case, it's arbitrary to put it either in one column or another. "Description" is a good option, "Identifier" might be another if we follow the same approach as the one used to version DOIs with one identifier per version.

**Comment by eblondel** [comment]
We have to distinguish 2 things:
* the `editionDate` that should be a date, It's mapped as specific date type in the Date column
* the `edition` is a description of the edition, I don't think it's an identifier (although it contributes to it). Indeed it would be a versioned DOI this could be used as "edition". This may feed further customization in the ISO 19115 action (with options, eg. use_doi_as_edition, etc)

**Comment by juliepierson** [comment]
Thank you ! We just tested :
- custom edition and edition date are taken into account, but 2 edition dates get created : one <gmd:date> with codeListValue = edition (which is not a valid value according to iso standards), and one <gmd:editionDate>
- when no edition date and edition are specified in the CSV, gmd:edition and gmd:editionDate are still created : ideally, we'd like no edition or edition date created when not specified in csv

**Comment by eblondel** [comment]
Can you re-install and check now?

Note aside: the ISO 191139 validation doesn't target the codelists you use. The standard gives default recommended values, but you are free to define your own codelist items (and your own vocabularies), the ISO 19139 will be valid. INSPIRE might say a different thing.

**Comment by juliepierson** [comment]
Wow, that's quick ! I retested, but <gmd:edition> and <gmd:editionDate> still get created when only publication:2021-03-04 is present in Date column of CSV. Thanks !

**Comment by eblondel** [comment]
Make sure Rstudio is restarted, the latter might run a cached version of past geoflow.

**Comment by juliepierson** [comment]
You're right, I forgot once again. All good now, thanks !!

**Comment by eblondel** [comment]
Great! :-)
