### ISSUE TITLE
no ISO category

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#106]
No ISO Category gets added to the metadata (perhaps because I don't know how to specify it in the CSV file ?)

**Comment by eblondel** [comment]
This is not available right now in the geometa action. This is open discussion where it should be handled in the geometa metadata model. Your ideas are welcome @juliepierson @mrouan @wheintz @juldebar

**Comment by mrouan** [comment]
I suggest to add a subtype topicCategory in the subject column. 
For example topicCategory:geoscientificInformation

**Comment by eblondel** [comment]
@mrouan i've realized that I had already added some feature for that in the ISO 19115 action, not under 'topicCategory' key, but under the ``topic`` key (sorry my memory failed :-) proof that the documentation effort we started early this month) is required. 

If you add `topic:biota,ocean` for example, it will add the two topic categories `biota` and ``ocean as you want in the ISO 19115.

@abennici can you please keep track of this _special_ subject `key` in your ongoing documentation work? thanks
