### ISSUE TITLE
onlineResource element gets created even when no URL specified in CSV

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#107]
If for example no website is specified for one of the contacts in the CSV file, an onlineResource element gets added with a missing url :
`<gmd:onlineResource>
                              <gmd:CI_OnlineResource>
                                 <gmd:linkage>
                                    <gmd:URL>
                                       <gmd:value gco:nilReason="missing"/>
                                    </gmd:URL>
                                 </gmd:linkage>
                                 <gmd:name gco:nilReason="missing"/>
                              </gmd:CI_OnlineResource>
                           </gmd:onlineResource>`
These elements must be manually removed to validate metadata in GeoNetwork.

**Comment by eblondel** [comment]
I will have a look to that and clean these empty online resources. However, Geonetwork validation should not break here, because the XML is valid since each tag is qualified with a ``gco:nilReason="missing"/>``. This is one proof that Geonetwork validation doesn't mean "ISO 19139 validation" (unfortunately), and the reason personnally I don't rely on the Geonetwork metadata validation system.

**Comment by eblondel** [comment]
The above commit should prevent this issue.

**Comment by juliepierson** [comment]
Thanks for this commit. I understand that the GeoNetwork validation is not perfect. The onLine resource elements still get created though (I enclose the XML metadata), when no website is specified for a contact. This results in message "Element 'gmd:URL' is a simple type, so it must have no element information item [children]. (Element: gmd:URL with parent element: gmd:linkage)" in GeoNetwork validation.

[bc7f3128-0ef1-4b05-8ab1-4c6170e9aa5d.zip](https://github.com/eblondel/geoflow/files/5950040/bc7f3128-0ef1-4b05-8ab1-4c6170e9aa5d.zip)

**Comment by eblondel** [comment]
Ok @juliepierson we have pushed some further fix, can you reinstall and check? Thanks

**Comment by juliepierson** [comment]
Thank you. I tried updating geoflow with
`require("remotes")`
`install_github("eblondel/geoflow", dependencies = c("Depends", "Imports"))`
but I get an error message during installation :
`Error : (converti depuis l'avis) /tmp/RtmpnYsKhZ/R.INSTALL158877d73dbb/geoflow/man/geometa_create_iso_19115.Rd:5: unknown macro '\item'`

**Comment by eblondel** [comment]
Apologies for this, please retest, should work now.

**Comment by juliepierson** [comment]
Thanks, geoflow installation is ok now. But there's an error during executeWorkflow :
`Error in createResponsibleParty(entity_contact) : `
`l'argument "role" est manquant, avec aucune valeur par défaut`
Metadata are not created. Is it an error in my csv ? I tried with different values for the Creator column, with the same result.

**Comment by eblondel** [comment]
No it's not in your csv, please reinstall now (apologies).

**Comment by juliepierson** [comment]
Yes, it works  ! Thanks a lot.

**Comment by eblondel** [comment]
Great!
