### ISSUE TITLE
adding distribution format

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#108]
No distribution format is added for GeoTiff files (ex. GeoTiff, version 1.0) (but perhaps I should specify it somewhere in CSV file ?)

**Comment by eblondel** [comment]
This is a missing feature AFAIK. cc to @juldebar, need to discuss this with him. I think that he requested the same some times ago. For this we may need to add a new column in the metadata table.

**Comment by juliepierson** [comment]
Ok, thank you. Adding a column in metadata table would be fine for us. We can take care of it in our script in the meantime.

**Comment by eblondel** [comment]
I have to discuss with @juldebar and @wheintz the matter, whether it is worth linking this to a vocabulary (eg. list of mime type controlled terms as listed in R `mime::mimemap`, quid of specialized formats not available there eg. geopackage, which deserves extending the previous list ), and also potentially to the data plugged in the "Data" column. This would make sense to inherit it from data files when available.

**Comment by juldebar** [comment]
I would not add a new column but rather manage with existing ones like Data

**Comment by eblondel** [comment]
We talked with @juldebar and agreed that it's worth adding a column ``Format``, that could be manually filled with formats, for now targeting "resource" (for resource formats as part of identification section), or ``distribution`` formats (as part of data distribution). The principle is the same as for the _relations_; Use a key (resource, format), and the value: a format. For now, if you need to add a format you need to add a new line.

Example: 
``
resource:image/tiff[GeoTIFF]_
resource:text/csv_
distribution:image/tiff[GeoTIFF]_
distribution:text/csv
``
I've mapped this improvement to https://github.com/eblondel/geometa/issues/176 where i've added a facility `buildFrom` on geometa `ISOformat` to try to map a mimetype (if you use a mime type as format) to inherit IANA mime type definition. If you want to test this you will need to update geometa from Github.

In a near future, we will try to provide a method to enrich these formats using the column Data, as it is already the case for enriching Relations, and spatial/temporal coverage. For the timebeing, at least this can be filled in the datasets description.

**Comment by juldebar** [comment]
and the good point is that "Format" is part of DCMI main metadata elements so we still stick to the standard:
https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/format

**Comment by juliepierson** [comment]
It works ! [GeoTIFF - v1.0] goes into <gmd:specification> whereas GeoNetwork uses <gmd:version>. It's ok for us though.

**Comment by eblondel** [comment]
Yes i know the `gmd:version` would be the appropriate field, but for the time being i don't an easy solution to map it through the pivot model. @juldebar might have an idea how to do this.

**Comment by juliepierson** [comment]
Ok, I understand, it's ok for us since it does not prevent validation of the metadata.

**Comment by eblondel** [comment]
Great! I suppose i can close the ticket. In case we come with a solution for version we will let you know
