### ISSUE TITLE
Problem with comma in CSV file

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#109]
If there is a comma somewhere in the "Rights" column of CSV file, text gets truncated at comma and metadata seems malformed : there's an error message when trying to access "complete view" in GeoNetwork.

**Comment by eblondel** [comment]
@juliepierson i've added a small control to prevent this, so you principle you should not have the text truncated. Another way to ensure text is not likely to be truncated is to double quote it, eg:

```
use:"This is some text that will not be truncated anyway, whatever content you put in it"
```

I invite to re do the publication test. in case you get malformed, please send me the link of the metadata so I can have a look.

**Comment by juliepierson** [comment]
Thanks, it works ! Sorry, I thought my text was already inside double quotes. But now it works even without double quotes.

**Comment by eblondel** [comment]
No problem, all this needs to be more documented, so your tests are more than welcome
