### ISSUE TITLE
Set keys available for 'Title' parameter in geoflow_entity

### ISSUE THREAD

**Issue by abennici** [eblondel/geoflow#113]
Title in geoflow entity sheet is manage actually as a characters string without using any keys. 
The DublinCore Metadata Initiative provide two subproperty to 'title' element : 
- title [https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/title/](url)
-  alternative [https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/alternative/](url)

`title` key should be manage as default title value i.e. **main title** and be assigned to past entries and a second key e.g. `alternative` or `subtitle` or `shortitle` can be implement and use for add a second level of information.

**Comment by eblondel** [comment]
Agreed on that. If you are ok you can submit a code proposal.
