### ISSUE TITLE
Simplify ISO formatage of entity contact by using function

### ISSUE THREAD

**Issue by abennici** [eblondel/geoflow#114]
ISO structuration of metadata element of entity contact list is use several time in code geometa-create-iso-19115. Create a function to reduce code.

**Comment by eblondel** [comment]
Agreed, we need to reduce amount of R code here, and a ``createResponsibleParty`` function is welcome, with parameters `contact` (geoflow entity contact used for the responsible party) and ``role`` (the target role according to ISO 19115).
Can you do it?

**Comment by abennici** [comment]
I can do it. 
Have you a suggestion to  'contact' parameter, ***contact*** is already use inside the loop include to the function?

**Comment by eblondel** [comment]
Use ``x`` as 1st arg, we avoid any issue then.
