### ISSUE TITLE
Improve subject handling in pivot model + ISO1115 action

### ISSUE THREAD

**Issue by eblondel** [eblondel/geoflow#118]
Among the improvements:
* addition of a ``key`` in `geoflow_subject` model. This will map in ISO 19115 action to the keywords type (eg. theme, project, platform, etc). The list of keys will be free, although in ISO 1115 values from the ISO codelist will be recommended as given in `geometa::ISOKeywordType$values()`
* if available the `name` (between square brackets [ ] in tabular entity handlers) and the `uri` will be used to associated a thesaurus in ISO 19115. This improvement will then allow to add a keyword set without necessarily adding a thesaurus .
* as a consequence the description `project` sub type will be removed, and supposed to be managed as `project` subject key.

**Comment by eblondel** [comment]
@juldebar @wheintz @mrouan I've consolidated the way to set-up subjects. In the past we couldn't properly manage keywordsSet without thesaurus, now we can, and the `key` used will be recycled as KeywordType, which opens much more building blocks. For example the `project` is one of ISO 19115 keyword type, so you can list projects associated to the metadata like this:

```
project:Project 1@http://project1,Project 2@http://project2
```

The thesaurus can be added by adding description in the `key` part, eventually an uri like this:

```
project[projects registry]@http://linktoregistry:Project 1@http://project1,Project 2@http://project2
```

A concrete example on `project`:

```
project[OpenAire projects registry]@https://explore.openaire.eu:BlueBridge@https://explore.openaire.eu/search/project?projectId=corda__h2020::6729c0ee95de7724deb60454bb4179de,BlueCloud@https://explore.openaire.eu/search/project?projectId=corda__h2020::fe9a6e5d52bc888ba0f5cb25e5207ed2
```

One important thing is that geoflow is not constraining any key for subject (we might provide in some future a table of recommended keys mapped to the different metadata standards and community practices). This is particularly valid for ISO19115 that doesn't impose any codelist, and then no keyword type lists. For example, we are free to define a subject ``key`` for Taxonomy.

They are also "special" keys:
* `topic` : allow to define Topic categories in ISO 19115
* `taxonomy`: used for EML taxonomic coverage (with the key name customizable in the action options).

(@abennici you may consider to update your ongnoing documentation work for Subject with the above elements)

**Comment by mrouan** [comment]
nice improvement !
