### ISSUE TITLE
Add action to generate Markdown for an entity

### ISSUE THREAD

**Issue by eblondel** [eblondel/geoflow#135]
The idea is to have a global action that can be used to generate a Markdown out of a `entity`. geoflow should provide a generic Markdown template used by default. The action should allow specify an alternative template as option.

In general having the capacity to generate a custom prettified markdown description of an entity metadata would be very useful, giving the flexibility of R markdown. This could also be useful to to be published and used in other data catalogue / interfaces such as Zenodo (attaching the markdown as first file resource which can then be previewed by Zenodo) or OpenFairViewer (for alternative metadata UI to Geonetwork or CSW ISO 191139 XML).

To discuss and further elaborate with @juldebar (codes already available I think?) and @abennici

**Comment by juldebar** [comment]
yes, there is an old piece of code here for that: https://github.com/juldebar/geoflow/blob/master/R/geoflow_action_create_Rmd.R
I used it 2 years ago to generate this kind of output from a geoflow entity: http://mdst-macroes.ird.fr/tmp/data_papertrash_rttp_school_sighting.html
I recently updated it and it would be a good opportunity for me to contribute to the package with this action if you help me to validate it.

**Comment by eblondel** [comment]
(bad issue referencing, should be #96, ignore above commits)
