### ISSUE TITLE
Experiment data software/accessor for Thredds Data Server (TDS)

### ISSUE THREAD

**Issue by eblondel** [eblondel/geoflow#172]
Based on this R package https://github.com/BigelowLab/thredds

**Comment by abennici** [comment]
Create a new accessor 'thredds' associate with a new software type 'thredds' to be able to source and download 'nc' files from a 'thredds' data server.
- [ ] The 'thredds' software should be contain two parameters (1) a  'x' parameter with the url of top level catalog ; (2) a 'prefix' parameter with the namespat to examine (e.g. **thredds**,**d1**)
- [ ] The 'accessor' must be powered by 'access:thredds_' and 'source: nc_file@relative_nodes_path/nc_file' in data entity sheet
