### ISSUE TITLE
Create entity handler for NetCDF-CF

### ISSUE THREAD

**Issue by eblondel** [eblondel/geoflow#180]
The idea is to develop an entity handler for Netcdf-CF file, handled through `ncdf4` package. Similar to `handle_entities_df`, we will create a `handle_entities_ncdf` function, where the `source` will be a NetCDF-CF file (local or remote). This function could be used as entity handler for a single NetCDF-CF file, or re-used to enrich entity specified in a tabular way (eg. gsheet) and where NetCDF-CF file is accessed through a data accessor (eg. Thredds #172).

**Comment by abennici** [comment]
Use standard keys registers to [ncdf template of noaa](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/#guidancetable) to detect metadata information and enrich entity
