### ISSUE TITLE
"Description" column of geoflow entities: issues with "abstract:" values management

### ISSUE THREAD

**Issue by juldebar** [eblondel/geoflow#20]
I noticed that "abstract:..." values are not anymore managed properly. Sometimes the content is cut, sometimes "abstract:" prefix is not  removed.
Other issue: even if II use a ";" to close the "abstract:" section, the fist line break ("\n") within the abstract section is interpreted as the end of the section.

**Comment by eblondel** [comment]
I'm fixing the issue with ``abstract:``. 

For the "\n" and ";" This is still a problematic. I can deactivate the split by \n for now as I understand this can be useful for description handling, but same could be for the ';'. Generally speaking we might need to find a character, symbol or special string that indicates we move to another line.

**Comment by eblondel** [comment]
@juldebar can you reinstall and test?

**Comment by juldebar** [comment]
I would say that this is the end if we have a pattern like ;\n" or ";\npurpose:" or ";\info:"
If we don't have one of those, then it should still be the content of the "abstract:"

**Comment by eblondel** [comment]
https://github.com/eblondel/geoflow/issues/21
