### ISSUE TITLE
setting parent metadata

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#212]
Hi,
I'm trying to set a parent metadata for a metadata. When doing it with geoflow XML looks like this :

`<gmd:parentIdentifier xmlns:gfc="http://www.isotc211.org/2005/gfc"`
`                         xmlns:gmi="http://standards.iso.org/iso/19115/-2/gmi/1.0"`
`                         xmlns:gmlcov="http://www.opengis.net/gmlcov/1.0"`
`                         xmlns:gmlrgrid="http://www.opengis.net/gml/3.3/rgrid">`
`      <gmx:Anchor xlink:href="https://catalogue/parent-identifier">parent-identifier</gmx:Anchor>`
`   </gmd:parentIdentifier>`

whereas when I do it by hand in GeoNetwork it looks like this :

`<gmd:parentIdentifier>
    <gco:CharacterString>parent-identifier</gco:CharacterString>
</gmd:parentIdentifier>`

When doing it with geoflow it does not show in the geonetwork interface, whereas it works ok when doing it from geonetwork.
Is this something to do with how GeoNetwork handles parent and children metadata ? Can I make it work with geoflow ?
Thanks again !

**Comment by eblondel** [comment]
Normally, any `gco:CharacterString` can be replaced by a `gmx:Anchor` tag which allows to specify an URI attached to the string. In geoflow, we map the parent identifier to a `parent` relation, which necessarily has an URI (although we have a control of it with `is.null` - see https://github.com/eblondel/geoflow/blob/master/R/geoflow_action_geometa_create_iso_19115.R#L90), so we always end up with an Anchor created, which is richer and valid vs ISO standard.
Maybe (?) that the UI template of Geonetwork for showing metadata fields is incomplete regarding the display of anchors, and it would deserve checking with Geonetwork team about the matter. cc @wheintz @fxprunayre in case they can shed light on this.

**Comment by juliepierson** [comment]
Thanks, I tested without specifying any link (just parent:parent-identifier) and it seems to work ok in geonetwork. I'll do like this for now until geonetwork can take into account the anchor tag. Cheers !
