### ISSUE TITLE
Error with 'spatialRepresentationType' for raster data

### ISSUE THREAD

**Issue by juliepierson** [eblondel/geoflow#215]
Hi,
Sorry to bother you again, but I have trouble solving this. I'm running geoflow to create and publish metadata in geonetwork for raster data, using a CSV table. Previously, the 'Data' column in my CSV was empty and all went well. I tried again 2 days ago (wih some new data as well as data I had previously successfully imported) and I had some error messages : first 
`Error in if (spatialRepresentationType == "vector") { : 
  l'argument est de longueur nulle`
And when I added "spatialRepresentationType:grid" in CSV (not at all sure about that) I got 
`Error in initialize(...): The data 'source' is mandatory`
I tried setting the source as well but I can't seem to make it work (and I don't want geoflow to upload my data so it doesn't seem necessary anyway).
I may be missing something obvious, thanks for your help !

**Comment by eblondel** [comment]
@juliepierson sounds we broke smthg recently with adding support for ISO 19115-2. just pushed some commit, can you reinstall and try again?

**Comment by juliepierson** [comment]
Thanks for your quick answer, I reinstalled (and restarted RStudio), I got :
`Error in action$fun(entity = entity, config = config, options = action$options) : 
  objet 'spatialRepresentationType' introuvable`

**Comment by eblondel** [comment]
more controls pushed, sounds 1st commit was not enough.

**Comment by juliepierson** [comment]
Thanks, now I get
`Error in entity$relations[sapply(entity$relations, function(x) { : 
  type 'list' d'indice incorrect`
But maybe it's totally unrelated ?

**Comment by eblondel** [comment]
can you send me your csv file?

**Comment by juliepierson** [comment]
[metadata_table_landemarais.csv](https://github.com/eblondel/geoflow/files/7209283/metadata_table_landemarais.csv)

**Comment by eblondel** [comment]
They are columns such as the relations one that are set to NA, leave the columns empty.

**Comment by juliepierson** [comment]
Thanks, I tried again leaving all NA cells empty, I get the same error message.

**Comment by eblondel** [comment]
i've checked some additional code that might cause this issue. Let me know

**Comment by juliepierson** [comment]
Yes !! It works ! Thanks for your time :)

**Comment by eblondel** [comment]
you're welcome. Apologies for the bugs, we are going to consolidate the tool adding integration tests for common workflows.

**Comment by eblondel** [comment]
@juliepierson  Another thing, if you try to reinstall geonapi package, I'm now supporting the new API starting with Geonetwork >= 3.2 I would welcome some test with the new geonapi and the geonapi action to publish metadata on geonetwork. Cf #213 
If this works well, I will try to add the thumbnail upload to the action #211

**Comment by juliepierson** [comment]
Great, I can test next week, I'll let you know how it goes.

**Comment by eblondel** [comment]
Great thanks @juliepierson . Whatever open question you have, you can ask it at https://gitter.im/geoflow-users/community unless you think there is a bug, keep using github issues!

**Comment by juliepierson** [comment]
Thanks, I'll do that !
