### ISSUE TITLE
Add description of entities and contacts in the wiki

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geoflow#216]
Hi,
I guess it's planned, but if it's not: the description of entity and contact metadata (attributes, syntax ..) is missing in the wiki.
Juliette

**Comment by eblondel** [comment]
@juliettefabre It's not yet on the wiki (still need to figure out how-to push this easily to the wiki), but it's in the doc folder. For any questions or documentation matter, better use the gitter https://gitter.im/geoflow-users/community or for dev aspects https://gitter.im/geoflow-developers/community Tickets should be used for bugs/feature requests/enhancements better
