### ISSUE TITLE
list_action_options fails for some ids

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geoflow#217]
Hi,
I just installed the most recent version of geoflow from github. Now, the `list_action_options` function fails for some ids (and not for others):
```
> list_action_options("geonapi-publish-iso-19139")
Erreur : $ operator is invalid for atomic vectors
> list_action_options("geometa-create-iso-19115")
Erreur : $ operator is invalid for atomic vectors
```
Thanks,
Juliette

**Comment by eblondel** [comment]
Thanks @juliettefabre that's known issue, i hadn't time to look at it. Thanks for reporting

**Comment by eblondel** [comment]
Apparently this issue was fixed already. Can't reproduce it. You may be running an old version of geoflow, or a cached one with Rstudio.

**Comment by juliettefabre** [comment]
I'm on the geoflow_0.0.20210730 version. That's the one installed when I run:
`withr::with_libpaths(new = "/usr/lib/R/site-library/", install_github("eblondel/geoflow", dependencies = c("Depends", "Imports"), force = TRUE))`
The https://github.com/eblondel/geoflow/issues/215 bug is resolved for me on this version, so I guess I have the most recent one?

**Comment by juliettefabre** [comment]
I removed and re-installed the package, still the same!

**Comment by eblondel** [comment]
no idea, i'll check on a rstudio server to see if I can reproduce. That's weird

**Comment by eblondel** [comment]
I've tested on several RStudio, R versions and OS. It works. Make sure your env is not polluted with 2 versions of geoflow, especially if you use RStudio server. I welcome some tests from @juldebar or @wheintz to see how it goes on their side.

**Comment by juliettefabre** [comment]
After removing and reinstalling geoflow a few times without any success, it works this morning (maybe due to my machine reboot).
