### ISSUE TITLE
WFS relation is considered as WWW:LINK-1.0-http--link with GN 3.10.0.6

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geoflow#219]
Hi,

I manage to specify WFS relations in my entities (column _Relation_, key _wfs_), but it's considered as WWW:LINK-1.0-http--link and not as WFS link (GeoNetwork 3.10.0.6).

My _Relation_ value: 
_wfs:observil_station[Stations WFS]@https://sig.oreme.org:8443/geoserver/sf/wfs_

Juliette

**Comment by eblondel** [comment]
Ok so far this is voluntary to have this coded as link. In GN we have to check backward compatibility as having links as WFS caused issues in some GNs. In addition there is no clear protocol handling in Geonetwork as we can have for WMS: https://github.com/eblondel/geoflow/blob/master/R/geoflow_action_geometa_create_iso_19115.R#L710 In general, being a ISO 19115 that is not ncessarily targeting a GN, there is need to study what's the best practice for that, eg. what they recommend in OGC? INSPIRE?

**Comment by juliettefabre** [comment]
In my GN, well interpreted WFS online ressources are defined with the **OGC:WFS** protocol.

**Comment by eblondel** [comment]
I know, but that's too vague unfortunately, since there is no information about the WFS version and operation.

**Comment by eblondel** [comment]
@juliettefabre new code has been pushed through #260 which aims to better handle the OGC relations, with distinction made between OGC base url (OGC:WFS, OGC:WMS, OGC:WCS) and specific download relations, based on OGC protocols, that can be enabled. All relations enrichments are active by default but can be deactivated as they are set as option of the geosapi action. If you have questions, feel free. If you can test and let me know if it works for you.

**Comment by eblondel** [comment]
@juliettefabre do you have comments before I close this ticket?

**Comment by juliettefabre** [comment]
Hello, I didn't take the time yet to test it, I try to  do it asap and let you know.

**Comment by juliettefabre** [comment]
Mhh, actually I was talking about geonapi, not geosapi!

**Comment by juliettefabre** [comment]
I don't get it. What should I do to test it?

**Comment by juliettefabre** [comment]
I use geoflow to read metadata and send them to GN. I updated geoflow, but WFS relation is still interpreted as HTTP link.

**Comment by eblondel** [comment]
Well, if you reinstall geoflow, try to assign a "wfs" relation in your metadata table, in the ISO 19115 it should be set as OGC:WFS link. For download link which is a generic type you will need to set either a "download" key as relation.

**Comment by eblondel** [comment]
See how relation key values are mapped to online resource protocols in ISO 19115 at: https://github.com/eblondel/geoflow/blob/master/inst/actions/geometa_create_iso_19115.R#L747

**Comment by juliettefabre** [comment]
Yet, it works! I guess I didn't load the correct geoflow .. Sorry.
