### ISSUE TITLE
Relative paths (data sources, local actions) in Data do not work

### ISSUE THREAD

**Issue by AmandineHenon** [eblondel/geoflow#222]
Pour lier des data en local, il faut noter le chemin absolu et non le chemin relatif !

**Comment by eblondel** [comment]
Could send me an example of your data column to see how it is structured?

I also need to know if it was run on ubuntu or windows os, and what was
your working directory ( see `getwd()` ) when you run this workflow.

Thanks in advance

Le mer. 6 oct. 2021 à 08:42, AmandineHenon ***@***.***> a
écrit :

**Comment by EmilieLerigoleur** [comment]
Hre is the example:
source:S073.xlsx@/home/ahenon/test-indores/S073.xlsx_
sourceType:other_
uploadType:other_
upload:true

Thanks to @AmandineHenon to give your OS and version.
Thanks to @wheintz to give the R version.

**Comment by eblondel** [comment]
Implementation should include:
- [ ] plug a util function `is_absolute_path` to check whether a resource is on absolute / relative path
- [ ] use this function in `geoflow_entity$copyDataToJobDir` in the case of local files handling (to fix the initial bug report)
- [ ] use this function in `geoflow_data` to handle properly local action scripts, whatever their path
- [ ] make sure that the local action scripts handling also distinguish the case of remote scripts with the appropriate regexp (see https://github.com/eblondel/geoflow/blob/master/R/geoflow_entity.R#L449)

**Comment by eblondel** [comment]
@EmilieLerigoleur @AmandineHenon  could you reinstall geoflow and test this? It should be fixed now. Thanks
