### ISSUE TITLE
Breaklines removed during upload

### ISSUE THREAD

**Issue by kikislater** [eblondel/geoflow#278]
- Actual behavior: Breaklines are removed during discussion with API

Discussed here : https://github.com/eblondel/geoflow/discussions/277

But finally tested with cURL and GeoNetwork API and breaklines are kept ! 

- Steps to reproduce : 
1. Create a metadata gsheets with breaklines
2. Run geoflow and keep generated xml file
3. Change id manually in xml to identify it later in GN
4. Run the following bash script to upload to your GeoNetwork:
```
#!/bin/bash
CATALOG=https://my.url/geonetwork
CATALOGUSER=admin
CATALOGPASS=password

# Clean session
rm -f /tmp/cookie;
# Authentification
curl -s -c /tmp/cookie -o /dev/null   -X GET   -H "Accept: application/json"   "$CATALOG/srv/api/me";
TOKEN=`grep XSRF-TOKEN /tmp/cookie | cut -f 7`;
# Test
curl   -X GET   -H "Accept: application/json"   -H "X-XSRF-TOKEN: $TOKEN" --user $CATALOGUSER:$CATALOGPASS -b /tmp/cookie   "$CATALOG/srv/api/me"

# Send XML
 curl -X POST -F "file=@metadata_test.xml" -H "Content-Type: multipart/form-data" -H "Accept: application/json"  -H "X-XSRF-TOKEN: $TOKEN" -b /tmp/cookie --user $CATALOGUSER:$CATALOGPASS $CATALOG/srv/api/records -v
```
 
5. Go to GeoNetwork and watch breaklines kept

**Comment by eblondel** [comment]
What is the version of GN that you used?

**Comment by eblondel** [comment]
Ok i've run a test workflow, and indeed breaklines are removed. ISO 19115/19139 is properly generated with [geometa](https://github.com/eblondel/geometa) action, but when passed to payload with [geonapi](https://github.com/eblondel/geonapi), we lose the breaklines. I will create a ticket there

**Comment by kikislater** [comment]
Tested in GeoNetwork 3.12.3.0 and 4.2.0

**Comment by eblondel** [comment]
Well after investigation, there seems to be no issue in geonapi, but instead `readISO19139` from [geometa](https://github.com/eblondel/geometa) that removes breaklines from texts....

**Comment by eblondel** [comment]
@kikislater i've fixed https://github.com/eblondel/geometa/issues/193 which was responsible of this issue. In _geoflow_, each ISO 19139 metadata produced and stored in the metadata directory is then read back in actions to publish metadata (with _geonapi_ or _ows4R_). The `readISO1139` was removing the line breaks. Please re-install [geometa](https://github.com/eblondel/geometa) from Github and next the issue should have disappeared. let me know

**Comment by kikislater** [comment]
Thanks it works ! 
@juldebar
