### ISSUE TITLE
Error when handling relation titles (citations) that include colon and/or comma symbols (often with co-authoring)

### ISSUE THREAD

**Issue by wheintz** [eblondel/geoflow#53]
Hi Emmanuel,
Geoflow cannot publish more than one relation (http type).
Many thanks,

 wilfried

**Comment by wheintz** [comment]
Hi again,
Finally it's possible to publish several http relations but it doesn't work with large titles ...

 wilfried

**Comment by eblondel** [comment]
Thanks @wheintz for reporting, indeed it's probably due to titles that include coma such as for distinguishing co-authors of a publication. I will look into a fix and let you know

**Comment by eblondel** [comment]
@wheintz I've applied a tentative fix, trying to handle your proposal (what we talked) about handling quotes for text that handle special characters used by geoflow to split among properties. The special characters are:
* _colon_ (:) used for distinguish a key (eg 'http') and its content; and 
* _comma_ (,) (used to distinguish several items for a given key).
The fix handles specific regular expression that exclude any of these characters that would be surrounded by doublequotes (" ").

Hence through the tabular description of entities, you can define for example a relation such as:

> http:"geoflow: R engine to orchestrate and run geospatial (meta)data workflows"["geoflow: R engine to orchestrate and run geospatial (meta)data workflows, powered by packages such as geometa, geosapi, geonapi, ows4R, and zen4R"]@https://github.com/eblondel/geoflow

In this example, I handle a http relation to be included in a ISO 19115 sheet, with:
* a title/name, that contains a _colon_, so I doublequote it: _"geoflow: R engine to orchestrate and run geospatial (meta)data workflows"_
* a description (within square brackets), that contains both _colon_ and various _comma_, so I doublequote it: _"geoflow: R engine to orchestrate and run geospatial (meta)data workflows, powered by packages such as geometa, geosapi, geonapi, ows4R, and zen4R"_

I've tested this approach and it works well. Let me know if it works for your use case
