### ISSUE TITLE
Spatial Extent troubles

### ISSUE THREAD

**Issue by wheintz** [eblondel/geoflow#54]
Hi again Emmanuel,

Spatial extent of datasets with native EPSG is not visible in geonetwork (although it's in the xml document).

Cheers,

 wilfried

**Comment by eblondel** [comment]
We need to investigate that, in particular how Geonetwork handles the spatial extent from an ISO 19139 metadata when the projection system is other than EPSG:4326. In a default configuration of Geonetwork, indeed the spatial extent widget breaks and doesn't display any map.

**Comment by eblondel** [comment]
At first view, it seems a bug in Geonetwork since EPSG:4326 seems hardcoded at https://github.com/geonetwork/core-geonetwork/blob/master/web-ui/src/main/resources/catalog/views/default/templates/recordView.html#L529

**Comment by eblondel** [comment]
@wheintz i've noticed some changes in geonetwork source code. If you upgraded your geonetwork to a recent version, you might want to check if it has been solved.

**Comment by olobry** [comment]
Hi Emmanuel, Wilfried,

I've recently upgraded GN to 3.10.6 and reimported the metadata using geonapi and I fall into the same trouble: the spatial extend does not show the background map in the metadata view. Do you now if the issue has been fixed ? or if there is a workaround ?

Cheers,
Olivier

**Comment by eblondel** [comment]
This is fixed in GN 4.x (maybe before but I'm not sure from which GN version exactly).
