### ISSUE TITLE
DOIs to be displayed as Thumbnails

### ISSUE THREAD

**Issue by juldebar** [eblondel/geoflow#56]
When a dataset already has a DOI, it would be nice to get it displayed (optionnal or not) with the native image (eg https://zenodo.org/badge/DOI/10.5281/zenodo.3629749.svg) as a thumbnail (by having it in the graphicOverview in the related OGC metadata).

**Comment by eblondel** [comment]
very good idea! I will probably use a generic badge (with https://img.shields.io) in that way it will be also applicable for DOIs coming from another repository than Zenodo: https://img.shields.io/badge/DOI-10.5281/zenodo.3629749-informational.svg
