### ISSUE TITLE
Describe spatial extent (or coverage) with terms in addition to eWKT

### ISSUE THREAD

**Issue by juldebar** [eblondel/geoflow#57]
It would be intersting to manage the third type of geographic descriptor for spatial extent (geographic identifier) by adding terms / keywords (in addition to the "bounding box" and more complicated features).
This could be possible by having these geograhic keywords  stored in a dedicated Thesaurus of the "Subject" column:
eg geonames:Paris,Toulouse

**Comment by eblondel** [comment]
Great idea. I would avoid to use the ``geonames`` since it is tightly related to https://www.geonames.org/ (which later could be plugged in geoflow if needed). Maybe "geography" would be ok? other suggestion?

**Comment by eblondel** [comment]
@juldebar i've pushed some first code that you can try.

Based on the following thesaurus declaration in gsheet : 

```
geography:France@https://www.geonames.org/3017382,Toulouse@https://www.geonames.org/2972315
```
The ``geometa-create-iso-19115`` will append 2 geographic identifiers as follows:

```xml
<gmd:geographicElement>
    <gmd:EX_GeographicDescription>
        <gmd:geographicIdentifier>
            <gmd:MD_Identifier>
               <gmd:code>
                 <gmx:Anchor xlink:href="https://www.geonames.org/3017382">France</gmx:Anchor>
               </gmd:code>
            </gmd:MD_Identifier>
        </gmd:geographicIdentifier>
     </gmd:EX_GeographicDescription>
</gmd:geographicElement>
<gmd:geographicElement>
    <gmd:EX_GeographicDescription>
         <gmd:geographicIdentifier>
             <gmd:MD_Identifier>
               <gmd:code>
                  <gmx:Anchor xlink:href="https://www.geonames.org/2972315">Toulouse</gmx:Anchor>
               </gmd:code>
           </gmd:MD_Identifier>
        </gmd:geographicIdentifier>
    </gmd:EX_GeographicDescription>
</gmd:geographicElement>
```

**Comment by juldebar** [comment]
yes geoname is just an example of controlled vocabulary but we should use a more generic name by default.
In previous cases, we used "geographic:keyword1,kw2.." before but it could fit better with 19115 labels of classes and properties by using "GeographicDescription" or "geographicIdentifier"

**Comment by eblondel** [comment]
@juldebar is ``geography`` thesaurus id ok for you? i think so, but in case we could further align on 19115 terms if better
