### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by wheintz** [eblondel/geoflow#97]
Dear Emmanuel,

When I try to publish several thumbnails in a metadata sheet whith geoflow, only the last one (in _relation_ column) is selected. Is it a normal behaviour ?

Many thanks,

 Wilfried

**Comment by eblondel** [comment]
Thanks I'll look into that asap and let you know.

**Comment by eblondel** [comment]
Hum, it should work if you have specified thumbnail as two lines:

```
thumbnail:mythumbnail1@http://mythumbnail1_
thumbnail:mythumbnail2@http://mythumbnail2
```

**Comment by wheintz** [comment]
Hi Emmanuel,

Here are my lines :
thumbnail:Vue générale@https://dynafor.toulouse.inrae.fr/data/st-caprais/vue_generale.jpg_
thumbnail:Vue détaillée@https://dynafor.toulouse.inrae.fr/data/st-caprais/dispositif.png

And here is my metadata sheet : https://dynids.toulouse.inra.fr:8443/geonetwork/srv/fre/catalog.search#/metadata/Donnees_croissance_arbres_chataigners_Saint-Caprais

As you can see, only the second thumbnail is visible. With the previous version of Geoflow, I didn't have this issue.

Cheers.

 wilfried

**Comment by eblondel** [comment]
@wheintz I've tried your lines, and for some reasons (we shoul look at it), the separator between the 2 lines was not a single \n but rather ``\r\n``. If you use the goole spreadsheet as entry point for entities, you should handle line separator with _ followed by ALT+ENTER, but it would be good to know how you led to have this ``\r\n``.
I've tried it on 2 different instances of R studio, deployed on Windows and Ubuntu 57 OS.

**Comment by eblondel** [comment]
@wheintz did it solve the issue?

**Comment by wheintz** [comment]
Yes! Many thanks Emmanuel, I'll pay attention to \r in the future ;-)
